# 애플리케이션 설정
app:
  name: "데이터 표준계약 검증 에이전트"
  version: "1.0.0"
  environment: "development"

# API 설정
api:
  host: "0.0.0.0"
  port: 8000
  cors_origins: ["*"]

# 데이터베이스 설정
database:
  url: "sqlite:///./data/database/contracts.db"
  echo: false

# Redis 설정
redis:
  url: "redis://localhost:6379"
  decode_responses: true

# OpenAI 설정
openai:
  api_key: "${OPENAI_API_KEY}"
  model: "gpt-4"
  embedding_model: "text-embedding-3-large"
  temperature: 0.1

# 파일 설정
files:
  max_size_mb: 10
  upload_dir: "./data/uploads"
  report_dir: "./data/reports"
  allowed_types: ["pdf"]

# 검색 설정
search:
  faiss_index_path: "./data/embeddings/faiss_index"
  whoosh_index_path: "./data/embeddings/whoosh_index"
  top_k: 10

# 로깅 설정
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./logs/app.log"
